### ISSUE TITLE
whenever run npx react-native run-android show error in mainActivity

### ISSUE THREAD

**Issue by thtRajasthaniGuy** [WrathChaos/react-native-typescript-boilerplate#10]
Error: AppData\Local\Android\Sdk\emulator\emulator\platform-tools\adb shell am start -n 
                              com.rntypescriptboilerplate/com.rntypescriptboilerplate.MainActivity
                              at makeError (E:\Project\React-native\react-native-typescript-boilerplate\node_modules\execa\index.js:174:9)

I have to open the app manually.

**Comment by thtRajasthaniGuy** [comment]
and it's crashing in android version 13.

**Comment by kuraydev** [comment]
Hello @govind1530 
Thank you so much for reporting this. 

How can I reproduce this issue? It works on my emulator and physical devices.  Did you finish the [Step by Step Guide](https://github.com/WrathChaos/react-native-typescript-boilerplate#-step-by-step-guide)

**Comment by thtRajasthaniGuy** [comment]
@WrathChaos  yes I  follow the all steps.

whenever run the command its through error , after the open app manually its work fine .
I using latest android studio , that might be problem?

**Comment by kuraydev** [comment]
It shouldn't be. Let me try to test it.

Have you tried to run it with command instead of Android Studio?

**Comment by thtRajasthaniGuy** [comment]
@WrathChaos  yes I always use command for run the app.

**Comment by kuraydev** [comment]
Hello @th1copycatninja 
Sorry was an extremely busy days.

I'm going to resolve this issue today :)

**Comment by kuraydev** [comment]
Hello @th1copycatninja 

Extremely sorry but I finally managed to spare some time on it. It is fixed on the latest commit. Please take a look at it :)
