### ISSUE TITLE
dyld: Library not loaded: /usr/lib/swift/libswiftWebKit.dylib

### ISSUE THREAD

**Issue by Pakile** [WrathChaos/react-native-typescript-boilerplate#11]
<img width="1263" alt="Screen Shot 2022-04-07 at 14 04 11" src="https://user-images.githubusercontent.com/76195408/162139838-62aeb6a0-f16a-4797-a949-6ddca1841bad.png">

When I run app with iOS 13, app crash

**Comment by kuraydev** [comment]
Hello @Pakile 
I tried to reproduce this issue but I could not. Have you followed this guide [Step by Step Guide](https://github.com/WrathChaos/react-native-typescript-boilerplate#-step-by-step-guide) 

Also, please try to delete derived data on the simulator.

**Comment by Pakile** [comment]
Hi @WrathChaos 
I'm sorry about this, this is my fault
