### ISSUE TITLE
crash on Android 

### ISSUE THREAD

**Issue by Yunnathai** [WrathChaos/react-native-typescript-boilerplate#14]
allow the step by step

npx react-native run-android

2022-04-30 00:35:07.143 25471-25471/com.rntypescriptboilerplate E/SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: library "libjsc.so" not found: needed by /data/app/~~GG6jzUDtVeutqC52waW0qw==/com.rntypescriptboilerplate-7kULpfl29FuwmzBUbx509Q==/lib/arm64/libjscexecutor.so in namespace classloader-namespace result: 0
2022-04-30 00:35:07.227 25471-25510/com.rntypescriptboilerplate A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 25510 (FlipperEventBas), pid 25471 (riptboilerplate)
2022-04-30 00:35:07.228 25471-25528/com.rntypescriptboilerplate E/QT: [QT]file does not exist
2022-04-30 00:35:07.238 25471-25528/com.rntypescriptboilerplate E/QT: [QT]file does not exist
2022-04-30 00:35:07.394 25471-25525/com.rntypescriptboilerplate E/OpenGLRenderer: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
2022-04-30 00:35:07.394 25471-25525/com.rntypescriptboilerplate E/OpenGLRenderer: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender

**Comment by kuraydev** [comment]
Hello @jamninetyfive 
Thank you for reporting this.

Can you try to run it with Android Studio? 
I need to reproduce this error to fix it

**Comment by Yunnathai** [comment]
same error between npx react-native run-android and Android studio

node@14
jdk8
android studio4.1.3

**Comment by kuraydev** [comment]
I will test it as well on my side.

**Comment by kuraydev** [comment]
@jamninetyfive I tested with a fresh clone, it works without any problem. 
Please try to delete your project and re-clone it.

**Comment by Yunnathai** [comment]
still not work , im using windows.

**Comment by kuraydev** [comment]
Can you please update android studio and try again? @jamninetyfive 
Also, please try to create the project with ` npx react-native init MyApp --template react-native-template-typescript` and let'see if it works or not

**Comment by kuraydev** [comment]
I am on MacOS so I could not try it on Windows but I will try

**Comment by Yunnathai** [comment]
Okay I'll try it later

**Comment by Yunnathai** [comment]
> 

it's work from this react-native-template-typescript. i can't update android studio because it's an online existing project

**Comment by kuraydev** [comment]
Strange, I will try to run it on windows because I could not reproduce it on MacOS. Can you share the reproducible repo with me?

**Comment by Yunnathai** [comment]
> Strange, I will try to run it on windows because I could not reproduce it on MacOS. Can you share the reproducible repo with me?

hi.i have tried it now in macos. same error like windows. so I think it may be a problem with the Android studio version.But it should not, can't you try it?

node@14
jdk8
android studio4.1.3

**Comment by kuraydev** [comment]
I am using `Arctic Fox` version of the Android. It can be it because you're using a bit old version. I cannot reproduce the problem :( 

Can't you have a chance to upgrade it?

**Comment by kuraydev** [comment]
https://github.com/facebook/react-native/issues/25537#issuecomment-548252592 

I am already fixing this bug in the Android part as you can see.

**Comment by kuraydev** [comment]
@jamninetyfive 
Since I cannot reproduce the issue, can you please try this one? 
https://stackoverflow.com/a/66535772/2247055

and this one:
https://stackoverflow.com/a/56778060/2247055

**Comment by nisarmalhi** [comment]
any update?

**Comment by kuraydev** [comment]
@nisarmalhi Do you have the same crash on android?

**Comment by kuraydev** [comment]
Hello @nisarmalhi, @jamninetyfive,
I guess I've fixed it. I updated the flipper version to `0.145.0`.

Please re-clone it, I've tested it. Waiting for your feedback

**Comment by nisarmalhi** [comment]
> @nisarmalhi Do you have the same crash on android?

Yes. i'm using macOS M1.

**Comment by nisarmalhi** [comment]
> Hello @nisarmalhi, @jamninetyfive, I guess I've fixed it. I updated the flipper version to `0.145.0`.
> 
> Please re-clone it, I've tested it. Waiting for your feedback

Thanks for quick update. Let me check.

**Comment by nisarmalhi** [comment]
> Hello @nisarmalhi, @jamninetyfive, I guess I've fixed it. I updated the flipper version to `0.145.0`.
> 
> Please re-clone it, I've tested it. Waiting for your feedback

@WrathChaos thank you so much. it's working for me.

**Comment by kuraydev** [comment]
@nisarmalhi Love to hear that :) 

@jamninetyfive Please take a look at it 


Also, please open ticket if you have any idea to improve this boilerplate :) Thank you

**Comment by jamninetyfive** [comment]
> 

It worked successfully. Thank you for your efforts. then i'll continue to explore your works.

**Comment by Yunnathai** [comment]
> Hello @nisarmalhi, @jamninetyfive, I guess I've fixed it. I updated the flipper version to `0.145.0`.
> 
> Please re-clone it, I've tested it. Waiting for your feedback

It worked successfully. Thank you for your efforts. then i'll continue to explore your works.
