### ISSUE TITLE
Need help for how to use events emitter

### ISSUE THREAD

**Issue by thtRajasthaniGuy** [WrathChaos/react-native-typescript-boilerplate#15]
Hello @WrathChaos  Thanks for this amazing typescript boilerplate.

i have a one question , i want to emit events , in this project you use events library can you please provide me a working example. 
i try to emit events as you already created  event file but it's not working.

Thanks in advance

**Comment by kuraydev** [comment]
Hello @th1copycatninja ,

Awesome question, I made a little documentation for how to use it

### [Event Emitter Doc](https://github.com/WrathChaos/react-native-typescript-boilerplate/blob/master/docs/event-emitter.md)

Please give me a feedback if it works for you or how can I improve the doc :)

**Comment by thtRajasthaniGuy** [comment]
@WrathChaos Thanks for the doc.
