### ISSUE TITLE
Need help about which one navigator i have to use.

### ISSUE THREAD

**Issue by thtRajasthaniGuy** [WrathChaos/react-native-typescript-boilerplate#16]
Hello 
@WrathChaos i confused about which navigator i have to use native-stack or stack navigator.

i am creating an app which have lots of animation and gesture also like button slide.

can you please help me out? it would be great help.
Thanks

**Comment by kuraydev** [comment]
Hello @th1copycatninja 
You can use both of the navigator. It totally depends on the use case. If you share the use-cases etc. I can try to help

**Comment by thtRajasthaniGuy** [comment]
use case: performance, and I also want to use animation and gesture handler in my app.
@WrathChaos

**Comment by kuraydev** [comment]
I cannot say anything with "use case: performance". It does not matter with performance, animations with navigator

**Comment by thtRajasthaniGuy** [comment]
okey understood thanks for help
