### ISSUE TITLE
React dependency error while installation 

### ISSUE THREAD

**Issue by osingh152** [WrathChaos/react-native-typescript-boilerplate#19]
![image](https://user-images.githubusercontent.com/29159715/179463109-ba2757b5-68f8-4e2d-a007-469d8b838ef8.png)

I tried to use your template but I am getting errors.
Please refer attached screenshot

Thansk

**Comment by kuraydev** [comment]
Hello @osingh152 
You should use node version `16.10.0` or lower. I just fixed the `engine` part of the boilerplate. 

Please try to re-clone and run the `npm i` again

**Comment by osingh152** [comment]
> Hello @osingh152 You should use node version `16.10.0` or lower. I just fixed the `engine` part of the boilerplate.
> 
> Please try to re-clone and run the `npm i` again

Thanks for fixing it, Great work you are doing:)

Please check the new issues https://github.com/WrathChaos/react-native-typescript-boilerplate/issues/21
