### ISSUE TITLE
Custom fonts do not seem to load in production build

### ISSUE THREAD

**Issue by FluffyDiscord** [WrathChaos/react-native-typescript-boilerplate#20]
Hi, I have added my custom fonts like this

![image](https://user-images.githubusercontent.com/10332247/180170206-e9b915e5-0743-45a8-a29d-813502ad8d7d.png)

added them to the theme like this 
![image](https://user-images.githubusercontent.com/10332247/180170398-d0026488-aad5-448b-b38b-63c2c22e7d35.png)

and use them like this (example)
![image](https://user-images.githubusercontent.com/10332247/180170789-2698da74-08ac-4d35-8cb8-4ae7e711c58e.png)

While this seems to work in dev mode, release android builds are not showing them properly and its using the default font

Running `npx react-native-asset` makes no difference.

Am I missing something ?

**Comment by kuraydev** [comment]
Hello @FluffyDiscord,
Please run this command and try again on Android release:

```
npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
```

It should generate the fonts for android as well.

**Comment by FluffyDiscord** [comment]
It seems that I was using some weird font, because as soon as I used the google fonts, it worked.
