### ISSUE TITLE
react-native run-android not working

### ISSUE THREAD

**Issue by osingh152** [WrathChaos/react-native-typescript-boilerplate#21]
Please see the error login attached image
![image](https://user-images.githubusercontent.com/29159715/180234429-45611209-a7f6-4ebd-9d3e-ee288da31d66.png)

**Comment by kuraydev** [comment]
Hello @osingh152 
Thank you for reporting this.

I tried to fresh clone this template and run the android with simple `npm i`. 
<img width="523" alt="CleanShot 2022-07-24 at 9 02 41@2x" src="https://user-images.githubusercontent.com/6813862/180660077-f65867c1-5cc4-496f-9446-c97c40517b1f.png">


I could not reproduce this problem. You should check your changes for vector-icons.
