### ISSUE TITLE
Can not run on windows 10

### ISSUE THREAD

**Issue by Schreibmann** [WrathChaos/react-native-typescript-boilerplate#22]
Just cloned repo and can't start with step by step guide. 
Getting "error Android project not found. Are you sure this is a React Native project? If your Android files are located in a non-standard location (e.g. not inside 'android' folder), consider setting `project.android.sourceDir` option to point to a new location."

**Comment by kuraydev** [comment]
Are you sure that you're trying to run the command on the correct path?
@Schreibmann

**Comment by kuraydev** [comment]
Hey again @Schreibmann 
[Version 3.4.0](https://github.com/WrathChaos/react-native-typescript-boilerplate/releases/tag/3.4.0) is released. 
Please try this version :)
