### ISSUE TITLE
Why not react 18?

### ISSUE THREAD

**Issue by minkgkyaw** [WrathChaos/react-native-typescript-boilerplate#23]
Sir, i think your boilerplate is out of date. you should switch react 18 and react native 0.69

**Comment by kuraydev** [comment]
Hello @minkgkyaw 
I upgraded **React 18** and **React Native 69+** and all other dependencies are upgraded :) 

#### [Version 3.4.0 🚀](https://github.com/WrathChaos/react-native-typescript-boilerplate/releases/tag/3.4.0)

Please try the new boilerplate :)
