### ISSUE TITLE
error while building android

### ISSUE THREAD

**Issue by afarzaneh-sc** [WrathChaos/react-native-typescript-boilerplate#24]
Hi I get the following error when I `npm run android`:

* Where:
Script 'D:\dev\users\amirhf\projects\test2\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 450       

* What went wrong:
A problem occurred evaluating script.
> Calling `[node, D:\dev\users\amirhf\projects\test2\node_modules\@react-native-community\cli\build\bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object      

  The current character read is 'i' with an int value of 105
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  info Run CLI with --verbose flag for more details.
  ^. Output: info Run CLI with --verbose flag for more details.

I have tried the solutions here: https://infinitbility.medium.com/unable-to-determine-the-current-character-it-is-not-a-string-number-array-or-object-in-react-f34c80d96e8e but none of them work!

I am running this on Windows

**Comment by kuraydev** [comment]
Hellooo, 

It seems there is something wrong with your environment or on your code. 

Here is the generated project which uses directly this boilerplate: 

https://github.com/WrathChaos/template-android-test

You should follow this[ step by step guide](https://github.com/WrathChaos/react-native-typescript-boilerplate#clean-up--simple-run)
