### ISSUE TITLE
tests SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by mutablestudio** [WrathChaos/react-native-typescript-boilerplate#6]
this is what I'm struggling with in my project and seems to be happening in yours as well - running `yarn test`:

```    /Users/afresina/Documents/projects/rn-code/react-native-typescript-boilerplate-master/node_modules/react-native/index.js:14
    import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      3 |  */
      4 |
    > 5 | import 'react-native';
        | ^
      6 | import React from 'react';
      7 | import App from '../App';
      8 |

      at Runtime.createScriptFromCode (../../../../.config/yarn/global/node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (__tests__/App-test.tsx:5:1)
```

I have tried all the jest config setups from SO and RN issues list and nothing seems to work. Do the tests run for you?

**Comment by kuraydev** [comment]
Hello @mutablestudio,

I still did not integrate the tests in this boilerplate however, integrating the Detox is on my first on the plan. Unfortunately, I have no idea about the `SyntaxError: Cannot use import statement outside a module` however I will also research about it and try to figure it out.

Thank you for reporting this.

**Comment by kuraydev** [comment]
Hello @mutablestudio,
I updated the boilerplate to version 3,
Can you try it and please tell me if this issue is still exist?

**Comment by mutablestudio** [comment]
sorry I couldn't test it but thanks for looking at it...
