### ISSUE TITLE
Error while Pod Install

### ISSUE THREAD

**Issue by premdasvm** [WrathChaos/react-native-typescript-boilerplate#7]
Hi, I just cloned the project, then did

1. npm I
2. npm run clean-up
3. npm i && npx pod-install

On the 3rd step I'm getting an error.

<img width="1440" alt="Screenshot 2022-01-17 at 12 14 30 PM" src="https://user-images.githubusercontent.com/14838550/149720760-49e0a2b5-cb6f-4d14-a628-47c2eb567db1.png">

When I disable flipper by commenting out this line on the pod file, it works.

`use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')`

**Comment by kuraydev** [comment]
Hello @premdasvm 
Thank you so much for the reporting the issue. 
I'm on it now!

**Comment by kuraydev** [comment]
Hello again @premdasvm 
I fixed the issues. Can you please delete your project and re-clone it? 

I'm waiting your feedback :)

**Comment by premdasvm** [comment]
Hey @WrathChaos 

Pod-Install is working fine now. although now when I'm trying to run the app it's shows some errors.

<img width="926" alt="Screenshot 2022-01-17 at 2 01 06 PM" src="https://user-images.githubusercontent.com/14838550/149734613-73946cfb-5dc5-44a6-b8aa-49ce903c00bb.png">


I'm not sure if it's related to my Dev Environment, I'm Using a M1 Air.

**Comment by premdasvm** [comment]
Hey @WrathChaos ,

So regarding the issue I just mentioned above, I followed this

 https://github.com/facebook/react-native/issues/30836#issuecomment-772810588
 
 and it seems to fix the issue while running, But I'm stuck with just a white screen after the splash screen shows. and the Metro isn't working. I'm confused in if it's some issue related to my Dev Environment.
 
<img width="1440" alt="Screenshot 2022-01-17 at 2 20 27 PM" src="https://user-images.githubusercontent.com/14838550/149738049-2a672096-b9dd-4e31-9c31-c6e3b8df61e2.png">

**Comment by premdasvm** [comment]
Hey @WrathChaos ,

Hey @WrathChaos ,

So regarding the issue I just mentioned above, I followed this

facebook/react-native#30836 (comment)

Now that I tweaked around a lil bit, I think I got  M1 Mac issue....not sure tho.

can you help me out here.?

<img width="1035" alt="Screenshot 2022-01-17 at 5 29 11 PM" src="https://user-images.githubusercontent.com/14838550/149765887-eab38c47-4e0c-4185-945e-f9fec8434ce0.png">

**Comment by kuraydev** [comment]
Hey @premdasvm 

I tried it on my Intel Chip Mac. It works without any problem. 

I guess you have error code 65, I will research it but I could not reproduce it in my environment.

**Comment by kuraydev** [comment]
Did you try this one @premdasvm ?

https://github.com/facebook/react-native/issues/30836#issuecomment-772830882

Remove the whole Flipper on PodFile.

**Comment by kuraydev** [comment]
@premdasvm Any update?
