### ISSUE TITLE
Error: Unable to resolve module ./index.android

### ISSUE THREAD

**Issue by Pakile** [WrathChaos/react-native-typescript-boilerplate#9]
Error: Unable to resolve module ./index.android when run `yarn android` in V3

**Comment by kuraydev** [comment]
I will look at it today!

Thank you for reporting this!

**Comment by Pakile** [comment]
hi @WrathChaos,
you have any update for this?

**Comment by kuraydev** [comment]
@Pakile 
Really sorry could not have time yesterday. I will fix it this evening for sure!

**Comment by kuraydev** [comment]
Hello @Pakile 
I fixed the issues, can you please try again?

**Comment by Pakile** [comment]
Thanks @WrathChaos
